name = "DocumentationGenerator"
uuid = "8f0d3306-d70b-5309-b898-24bb6ab47850"
authors = ["Sebastian Pfitzner <pfitzseb@physik.hu-berlin.de>", "Simon Danisch <sdanisch@gmail.com>", "Venkatesh Dayananda <venkatesh@juliacomputing.com>"]
repo = "https://github.com/JuliaDocs/DocumentationGenerator.jl.git"
version = "0.7.10"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GitForge = "8f6bce27-0656-5410-875b-07a5572985df"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
GithubMarkdown = "ecb7cac2-dae3-4a6f-a5f6-8274be99c6cb"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTMLSanitizer = "9a15a9f4-ddd5-46ee-89fc-c219f813dd6f"
Highlights = "eafb193a-b7ab-5a9e-9068-77385905fa72"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Org = "587fedb0-ad84-11e9-2bd6-d15ea4be1f9e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
AbstractTrees = "0.4"
Documenter = "0.24, 0.25, 0.26, 0.27"
GitForge = "0.4"
GitHub = "5.1, 5.2, 5.3, 5.4"
GithubMarkdown = "0.2"
Gumbo = "0.8"
HTMLSanitizer = "0.2"
Highlights = "0.4, 0.5"
JSON = "0.21"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
