stargazers_count = 67
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "JuliaWeb"
installs = true
license = "MIT License"
version = "5.0.2"
description = "A Julia package for interfacing with GitHub"

[[contributors]]
name = "jrevels"
contributions = 104
[[contributors]]
name = "WestleyArgentum"
contributions = 100
[[contributors]]
name = "Keno"
contributions = 27
[[contributors]]
name = "KristofferC"
contributions = 23
[[contributors]]
name = "astrieanna"
contributions = 7
[[contributors]]
name = "ararslan"
contributions = 4
[[contributors]]
name = "jiahao"
contributions = 3
[[contributors]]
name = "staticfloat"
contributions = 2
[[contributors]]
name = "nkottary"
contributions = 2
[[contributors]]
name = "tkelman"
contributions = 2
[[contributors]]
name = "femtocleaner[bot]"
contributions = 2
[[contributors]]
name = "arnavs"
contributions = 1
[[contributors]]
name = "DilumAluthge"
contributions = 1
[[contributors]]
name = "fredrikekre"
contributions = 1
[[contributors]]
name = "IainNZ"
contributions = 1
[[contributors]]
name = "quinnj"
contributions = 1
[[contributors]]
name = "jbn"
contributions = 1
