stargazers_count = 26
license_url = ""
doctype = "default"
owner = "JuliaStats"
installs = true
license = "Other"
version = "0.9.6"
description = "Uniform Interface for positive definite matrices of various structures"

[[contributors]]
name = "lindahua"
contributions = 50
[[contributors]]
name = "andreasnoack"
contributions = 34
[[contributors]]
name = "dmbates"
contributions = 10
[[contributors]]
name = "scheidan"
contributions = 8
[[contributors]]
name = "yuyichao"
contributions = 7
[[contributors]]
name = "ararslan"
contributions = 4
[[contributors]]
name = "jmxpearson"
contributions = 4
[[contributors]]
name = "Nosferican"
contributions = 3
[[contributors]]
name = "simonster"
contributions = 3
[[contributors]]
name = "janmtl"
contributions = 2
[[contributors]]
name = "johnmyleswhite"
contributions = 2
[[contributors]]
name = "simonbyrne"
contributions = 2
[[contributors]]
name = "alyst"
contributions = 1
[[contributors]]
name = "bkamins"
contributions = 1
[[contributors]]
name = "cbecker"
contributions = 1
[[contributors]]
name = "crbinz"
contributions = 1
[[contributors]]
name = "IainNZ"
contributions = 1
[[contributors]]
name = "jiahao"
contributions = 1
[[contributors]]
name = "kmsquire"
contributions = 1
[[contributors]]
name = "KrisDM"
contributions = 1
[[contributors]]
name = "mohamed82008"
contributions = 1
[[contributors]]
name = "oschulz"
contributions = 1
[[contributors]]
name = "lendle"
contributions = 1
[[contributors]]
name = "scidom"
contributions = 1
[[contributors]]
name = "tkelman"
contributions = 1
[[contributors]]
name = "femtocleaner[bot]"
contributions = 1
[[contributors]]
name = "kshramt"
contributions = 1
[[contributors]]
name = "matbesancon"
contributions = 1
